# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5342fa7a17a15913ffb7d5a1070eb2433314b1c4d3c17f0b74b676bfc67f00808c4155fe5d75ef451599120e202321fd34bd88283970deda3ee943042c0ecbe

test:
  secret_key_base: 01db83c7f16fe755d78c5fb8b40fdad802dc4e8ad5fe81631209756b0f4002b965e454fb6827043261852ff086999400e891fb9cfcdd09f2e652f4a1e9f41eb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
